### ISSUE TITLE
https://github.com/llambda/brute-knex/issues/4

### ISSUE THREAD

**Issue by kirrg001** [llambda/rust-reverse-geocoder#5]
Hey! 

I saw you are having activity in this repo.

Could you please, please read https://github.com/llambda/brute-knex/issues/4? I really don't want to push a fork of your repo to npm. 

Thanks!
@llambda

**Comment by llambda** [comment]
Yeah sorry, I never got a notification. Will add you.

**Comment by kirrg001** [comment]
@llambda Great! Fantastic!

Don't forget about the npm permissions, otherwise i am not allowed to publish :)
