### ISSUE TITLE
Replace old dependencies for reverse-geocoder

### ISSUE THREAD

**Issue by jqnatividad** [llambda/rust-reverse-geocoder#7]
Currently, it uses rustc-serialize which has been deprecated in favor of serde (https://crates.io/crates/rustc-serialize) and quick-csv, which depends on rustc-serialize and has not been updated in 5 years.

**Comment by gx0r** [comment]
Thanks @jqnatividad I will replace those crate usages and update this project.

**Comment by gx0r** [comment]
Updated and released v3.0.0.

**Comment by jqnatividad** [comment]
Thanks!!!! Works perfectly!
